### ISSUE TITLE
FaceVerificator.compare_two does not exist

### ISSUE THREAD

**Issue by levants** [meownoid/face-identification-tpe#1]
Hello

I'm trying to run test on two images (with default size), I found call of FaceVerificator.compare_two in test.py which does not exists in FaceVerificator
```python
t1 = io.imread('/home/egor/Downloads/1.jpg')
t2 = io.imread('/home/egor/Downloads/2.jpg')
y = fv.compare_two(0.825, t1, t2)
```

Can you give me a tip for face embeddings extraction and face comparison for images of any size.

regards

**Comment by meownoid** [comment]
Sorry, it's an old debug code. I've deleted it and added `demo_app0.py` in e83e6a1 which is simple console application which shows how to process two images.

Use `compare_many` instead of `compare_two`. It takes as a parameters distance, matrix which rows are embeddings of the first image and matrix which rows are embeddings of the second image and returns two matrices of equal size.

First matrix is a score matrix which [i, j] elment shows the similarity between i-th face on the first image and j-th face on the second image. Second matrix contains 1 where this value is greater than dist and 0 where is not.
