### ISSUE TITLE
what the dev_protocol in train_tpe file is?

### ISSUE THREAD

**Issue by zhuzzjlu** [meownoid/face-identification-tpe#7]
```
def test():
    dev_emb2 = tpe_pred.predict(dev_emb)
    tsc, isc = get_scores(dev_emb2, dev_protocol)
    eer, _, _, _ = calc_metrics(tsc, isc)
    return eer

def get_scores(data_y, protocol):
    data_y = data_y / np.linalg.norm(data_y, axis=1)[:, np.newaxis]
    # scores = data_y @ data_y.T
    scores = np.matmul(data_y,data_y.T)
    return scores[protocol], scores[np.logical_not(protocol)]
```
 I would like to know how to generate dev_protocol file.

Because I generate this by myself and get an error "IndexError: index 1511 is out of bounds for axis 0 with size 1000"

I have splited the train data and take 10,000 to do training, take 1000 to do dev.
the tag in dev_protocol like this: 

array([1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511,
       1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511,
       1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511, 1511,
       ... ... .........
       1524, 1524, 1524, 1524, 1524, 1524, 1524, 1524, 1524, 1524])

**Comment by meownoid** [comment]
Ok, `dev_protocol` file contains the binary matrix, where `1` on the position `(i, j)` means that `i`-th and `j`-th images belong to the same person and `0` otherwise.

For example, assume that our development set contains 6 images of 2 persons: images `1,3,5,6` belongs to the first person and images `2, 4` belongs to the second person. Development protocol then is the `6x6` matrix:
```
   1 2 3 4 5 6
[
1 [1,0,1,0,1,1],
2 [0,1,0,1,0,0],
3 [1,0,1,0,1,1],
4 [0,1,0,1,0,0],
5 [1,0,1,0,1,1],
6 [1,0,1,0,1,1]
]
```

Now you process this `6` images through the network to obtain `6` embedding vectors. It's the `6x256`matrix (`data_y`). Then you normalize this matrix along the axis `1` and multiply by itself transposed to get the `6x6` `scores` matrix. This matrix contains cosine distance between all possible combinations of embedding vectors.

So, `scores[protocol]`is all the **target**-scores (which should be accepted) and `scores[np.logical_not(protocol)]` is all the **imposter** scores (which should be rejected). And now you can calculate an EER.

**Comment by zhuzzjlu** [comment]
Thank you for your reply!
But if I have many person in dev, how to design this dev_protocol file

**Comment by meownoid** [comment]
The simplest way is to loop over the labels list:

```python
labels = [1,2,3,1,1,1,3,4]

protocol = np.zeros((len(labels), len(labels)), dtype=np.bool)

for i in range(len(labels)):
    for j in range(len(labels)):
        if labels[i] == labels[j]:
            protocol[i, j] = 1

np.save('dev_protocol', protocol)
```
I hope you've got the main idea.

**Comment by zhuzzjlu** [comment]
Thank you very much!
I would like to know how to process more face label (more than two) in dev_protocol, cause according to your statement, I can only deal with two classification.

**Comment by zhuzzjlu** [comment]
Thank you for your patience, I get this.
Best regard to you.
